language: java
jdk:
- oraclejdk8
  
before_deploy: cp .travis.settings.xml $HOME/.m2/settings.xml
deploy:
  provider: script
  script: mvn deploy
  on:
    branch: master

cache:
  directories:
  - .autoconf
  - $HOME/.m2
