language: java
jdk:
- oraclejdk8

script:
  - cp .travis.settings.xml $HOME/.m2/settings.xml
  - mvn clean install
  - mvn deploy
  
env:
  global:
  - secure: XLcfE2hcKDW23hILLgARFjrVEqHGIOeXeqtLZ36zQsLdCFAjRiGDo1K6VroGX94YmBOvHe7EUgQStYw66iPkdHNGTMQGP/tLXJ7stsotNsg+FJvpSfC38TwbSoS5C+NJyJrsEDKPw90YzxmzZfYlIKfK24hDLjvg3+m2AH4PTHJ6kuB8JxujFmkMgzBFQuVsfNqa5BYblqf33tE4vDMN4NhJmRhxuOvvKxGbyZb3R7QFOVQK0dcNPYnjbV4P2WaBAaXRpBC07Jluc/y5CSvKGxnt89kUoJFU4iCuO/BRf9YUi8VpQDMRAaGkBqvBBgFo5XZjDnh6nHmPCA+CULoWJikMmN1CIQ/RirGY3iUUFEkpismDFXNT6tdM8mPr6yTlHMoSgSc49MIMcw8lpgXWA4C6yQl2OA4cDDHwg9TVv8/iVwZ62PizyMzwEYiKCVpbd3hlx8OBt7hTtor2pKNLXByL2m3LzKDAvZvoYMOpzqmdlkCzp0IlcnJ1yrqbxKqN3eFyb/HqdQ/O5nOhWMhvJj6VipQHtXMdNOQkwPy4NRmRZAZ3/XoFBmTTXXvfbEft9D1FJTuCg/anL6/u3LkTzRBViHB5FaVjvREIMFXJL10uBnvDyjBLvvweQBY3qvb6OlqDvcik7QmyQtPvoA+MgNOgaoMASK8XSxmB2lmlWmg=
  - secure: s0LomonGuGANQCd/aeKP8ErGmnKPMiIz1HGVU9Wvfu4wGdJrgQI+Bsk4ClZjkZgA/xyf0n7rtlNnlyLtTIBOUtZ2XyGW9KqXn7VBWDQ/3vsSrY6z7RRGHc5xfvsI+L0WsLxZvQDqFJsKs0ZYum3ZJW27R6FvaQOu+jlgju0jirwR9ix6M3V+zDt38DaGHD1upUo2aK0EB6zq96w+JMB6v3z8fQHpWwXt2mfLmfQ3YV4agyEE0xc+eJHNqsmNNufx2cgjTfS1xLPYKB7WKKnwKFXZ12ajpyiF7O6KoDXzPmB4NTJQhS1u7Bg1/qIJVYRkhE0dN9eZ7DqnWMtau8fCOPxCjjnkL05yQwGABQdj4RfHqP0u72Fn8+C0YUBPkMvd+KSmz48Y+HGgJ7Lq/E3pUdTO6e1IRkaYzZaqv/4G3E7tRf1vVLK/DRPMvcEw24TQPA9/NgFCb+BYu0mzNAjysyfqwgQqRqgLwtfWnQflMt3VD54SJIam6oL7YsKiw6IzHZoK0Cfwu1EfoQ8h9uUCSDfscQ5OpN49JaLmtNWdHTjaj2p95HZTeTrfbyNf2v23bWX9th9o4mTFSzqQ6NKG53r/p8l/77vjV4lX5nZEkdqJ69SEt5+Pmr1CkEIzOKq2yYkCnGBGYBoymijKk1qL9oylnFOet0dFL2kIm9I9MPU=
